In [5]:
import numpy as np

1. Stwórz macierze A i B o wymiarach  1000×1000 zawierające wartości A[i,j]==i*3-j*5 i B[i,j]==np.sqrt(A[i,j]) (Zauważ, że to wymaga wartości urojonych, a więc macierzy typu complex64 i wartość sqrt(-1) ->.j)

In [11]:
def create_matrix(m, n):
    arr1 = np.zeros((m, n), dtype=np.complex)
    for i in  range(m):
        for j in range(n):
            arr1[i][j] = 3*i -5*j
            
    arr2 = np.sqrt(arr1)
    return arr1, arr2

In [12]:
create_matrix(4, 4)

(array([[  0.+0.j,  -5.+0.j, -10.+0.j, -15.+0.j],
        [  3.+0.j,  -2.+0.j,  -7.+0.j, -12.+0.j],
        [  6.+0.j,   1.+0.j,  -4.+0.j,  -9.+0.j],
        [  9.+0.j,   4.+0.j,  -1.+0.j,  -6.+0.j]]),
 array([[0.        +0.j        , 0.        +2.23606798j,
         0.        +3.16227766j, 0.        +3.87298335j],
        [1.73205081+0.j        , 0.        +1.41421356j,
         0.        +2.64575131j, 0.        +3.46410162j],
        [2.44948974+0.j        , 1.        +0.j        ,
         0.        +2.j        , 0.        +3.j        ],
        [3.        +0.j        , 2.        +0.j        ,
         0.        +1.j        , 0.        +2.44948974j]]))

#### 2. Napisz funkcję poz(indeksy, shape), która dla zadanej krotki indeksów zwraca liniową pozycję elementu o zadanych indeksach w wielowymiarowaj macierzy o kształcie shape. Np. poz([1,1,1],(2,2,2)) daje 7, zaś poz([0,1,0],(2,2,2)) daje 2.  To jest praca domowa za ekstra 1 punkt.

In [13]:
def poz(indices, shape):
    shape = list(shape)
    shape.append(1)
    return sum([indices[i] * np.prod(shape[i+1:]) for i in range(len(indices))])


print(poz([1,1,1], (2,2,2)), poz([0,1,0], (2,2,2)))

7 2


3. Napisz program, który  zmienia znak elementów w macierzy B, których suma indeksów jest nieparzysta, na ujemny. Warto rozważyć wykorzystanie  mnożenia macierzy i ew. broadcasting.

In [8]:
np.repeat((np.arange(3) % 2).astype(bool)[np.newaxis], 3, axis=0)

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [10]:
def sign_odd(b):
    if np.prod(b.shape) % 2 == 1:
        indicies = (np.arange(np.prod(b.shape)) % 2).astype(bool).reshape(b.shape)
    else:
        indicies = np.repeat((np.arange(b.shape[0]) % 2).astype(bool)[np.newaxis], b.shape[1], axis=0)
    print(indicies)
    b[indicies] = -b[indicies]
    return b

sign_odd(np.arange(16).reshape(4,4))

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True False  True]]


array([[  0,  -1,   2,  -3],
       [  4,  -5,   6,  -7],
       [  8,  -9,  10, -11],
       [ 12, -13,  14, -15]])

#### 4. korzystając z metody sort() , posortuj macierz 3-wymiarową wg. drugiej współrzędnej i obejrzyj wynik ze zrozumieniem tego co się wydarzyło.

In [14]:
arr = np.random.rand(2,2,2)
arr

array([[[0.15179076, 0.09914572],
        [0.10438487, 0.57560481]],

       [[0.55926398, 0.47631744],
        [0.07116614, 0.60891502]]])

In [15]:
arr[:, 0]

array([[0.15179076, 0.09914572],
       [0.55926398, 0.47631744]])

In [16]:
np.sort(arr, axis=1)

array([[[0.10438487, 0.09914572],
        [0.15179076, 0.57560481]],

       [[0.07116614, 0.47631744],
        [0.55926398, 0.60891502]]])

5. (*)Korzystając z funkcji frompyfunc() napisz funkcje wektorowe, które liczą a) sumę kwadratów dwóch macierzy  (dwie macierze do jednej)
b) iloraz i resztę z dzielenia całkowitoliczbowego przez 17 (jedna macierz wejściowa i dwie macierze wyjściowe)

In [17]:
def matrix_square_sum(x,y):
    return x**2 + y**2

sum_sq = np.frompyfunc(matrix_square_sum, 2, 1)
sum_sq(np.arange(4).reshape(2,2), np.arange(4).reshape(2,2))

array([[0, 2],
       [8, 18]], dtype=object)

In [18]:
def matrix_div_17(x):
    return (x // 17, x % 17)

div_17 = np.frompyfunc(matrix_div_17, 1, 2)
div_17(np.arange(20, 24).reshape(2,2))

(array([[1, 1],
        [1, 1]], dtype=object), array([[3, 4],
        [5, 6]], dtype=object))

###### 6. Korzystając z modułu time, porównaj prędkość funkcji liczących N kolejnych potęg dwójki – na liście i w wektorze. Dla jakich wartości N warto używać macierzy?

In [19]:
def arr_power(n):
    arr = np.zeros(n)
    for i in range(n):
        arr[i] = 2**i
    return arr

def lst_power(n):
    lst = []
    for i in range(n):
        lst.append(2**i)
    return lst

In [20]:
%time
lst_power(1)

%time
arr_power(1)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 16.2 µs
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 12.6 µs


array([1.])

In [21]:
%time
lst_power(2)

%time
arr_power(2)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 13.1 µs
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 11.4 µs


array([1., 2.])

In [22]:
%time
lst_power(3)

%time
arr_power(3)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 13.1 µs
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 11.4 µs


array([1., 2., 4.])

In [23]:
%time
lst_power(4)

%time
arr_power(4)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 11.2 µs
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 10.7 µs


array([1., 2., 4., 8.])

In [24]:
%time
lst_power(5)

%time
arr_power(5)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 12.2 µs
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 11.4 µs


array([ 1.,  2.,  4.,  8., 16.])

In [25]:
%time
lst_power(6)

%time
arr_power(6)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 11.4 µs
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 10 µs


array([ 1.,  2.,  4.,  8., 16., 32.])

In [27]:
%time
lst_power(7)



%time
arr_power(7)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 11.2 µs
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 10.7 µs


array([ 1.,  2.,  4.,  8., 16., 32., 64.])