In [2]:
import numpy as np

Ax = b

Lx = b

Ux = b

A = LU

In [5]:
def l_backward(L, b):
    x = np.zeros_like(b)
    x[0] = b[0]
    for i in range(len(L)):
        for j in range(i):
            b[i] -= L[i][j] * x[j]
        x[i] = b[i]
    return x

In [6]:
L = np.array([[1,0,0], [1,1,0], [1,1,1]])
b = np.array([1,1,1])

In [7]:
l_backward(L, b)

array([1, 0, 0])

In [ ]:
def u_forward(U, b):
    x = np.zeros_like(b)
    x[0] = b[0]
    for i in range(len(U)):
        for j in range(i, len(U)):
            b[i] -= U[i][j] * x[j]
        x[i] = b[i]
    return x

uzupełnienie Schura

In [75]:
def lu_decomp(A):
    L = np.zeros_like(A)
    U = np.zeros_like(A)
    L[0, 0] = 1
    U[0, 0] = A[0, 0]
    L[1:, 0] = A[1:, 0] / A[0,0]
    U[0, 1:] = A[0, 1:]
    if len(A) == 2:
        L[1,1] = 1
        U[1,1] = A[1,1] - L[1,0] * U[0,1]
        return L, U
    # uzupełnienie schura
    outer = np.outer(L[1:, 0], U[0, 1:])
    L[1:, 1:], U[1:, 1:] = lu_decomp(A[1:, 1:] - outer)
    return L, U

In [80]:
A = np.array([[2,4,3,5], [-4,-7, -5, -8], [6,8,2,9],[4,9,-2,14]], dtype='float')

In [81]:
l, u = lu_decomp(A)

In [82]:
l

array([[ 1.,  0.,  0.,  0.],
       [-2.,  1.,  0.,  0.],
       [ 3., -4.,  1.,  0.],
       [ 2.,  1.,  3.,  1.]])

In [83]:
u

array([[ 2.,  4.,  3.,  5.],
       [ 0.,  1.,  1.,  2.],
       [ 0.,  0., -3.,  2.],
       [ 0.,  0.,  0., -4.]])